title: Scott Clark
logo: ![Me](https://github.com/pages-themes/minimal/assets/146842625/1fc16251-cbf5-4e95-8bf6-4011613d9a57)
description: Owner/Operator of Leonardos Convenience Store
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme


