title: Scott Clark
logo: <img src=" docs/assets/Me.jpg" width="300">
description: Owner/Operator of Leonardos Convenience
show_downloads : false 
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme


